// <auto-generated />
namespace ChapubelichBot.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.4.4")]
    public sealed partial class changedsizesofUsercolumns : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(changedsizesofUsercolumns));
        
        string IMigrationMetadata.Id
        {
            get { return "202010111819292_changed sizes of User columns"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
