// <auto-generated />
namespace Chapubelich.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.4.4")]
    public sealed partial class Balanceofusershasbeenconvertedtolong : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(Balanceofusershasbeenconvertedtolong));
        
        string IMigrationMetadata.Id
        {
            get { return "202010072310518_Balance of users has been converted to long"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
