// <auto-generated />
namespace ChapubelichBot.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.4.4")]
    public sealed partial class splittableaddedcomplimentedbool : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(splittableaddedcomplimentedbool));
        
        string IMigrationMetadata.Id
        {
            get { return "202010171116491_split table, added complimented bool"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
